# vim:ft=kitty

## name: Custom Light Theme (Aligned Palette)

# The basic colors
foreground              #000000
background              #ffffff
selection_foreground    #000000
selection_background    #e4e4e4

# Cursor colors
cursor                #000000
cursor_text_color     #ffffff

# kitty window border colors
active_border_color     #0057d1
inactive_border_color   #95a99f

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #f5f5f5
inactive_tab_foreground #565f73
inactive_tab_background #f4f4ff

# The basic 16 colors

# black
color0  #565f73
color8  #95a99f

# red
color1  #d11500
color9  #d92f2f

# green
color2  #008b0c
color10 #4fb324

# yellow (gold spectrum)
color3  #ff8c00
color11 #de7a35

# blue
color4  #0057d1
color12 #0000ff

# magenta / purple range
color5  #d100bf
color13 #a022c5

# cyan / greyblue
color6  #008c99
color14 #14a8bb

# white / foreground scale
color7  #f5f5f5
color15 #000000
