# vim:ft=kitty

## name: Custom Light Theme
## blurb: Light theme with white background and adjusted palette

# The basic colors
foreground              #000000
background              #ffffff
selection_foreground    #000000
selection_background    #e4e4e4

# Cursor colors
cursor                  #000000
# cursor_text_color       #ffffff

# kitty window border colors
active_border_color     #0057d1
inactive_border_color   #95a99f

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #f5f5f5
inactive_tab_foreground #565f73
inactive_tab_background #f4f4ff

# The basic 16 colors
# black
color0  #565f73
color8  #95a99f

# red
color1  #d11500
color9  #f40064

# green
color2  #008b0c
color10 #008c99

# yellow
color3  #ff8c00
color11 #634b2f

# blue
color4  #0057d1
color12 #c486f0

# magenta
color5  #d100bf
color13 #c486f0

# cyan
color6  #008c99
color14 #56b6c2

# white
color7  #f5f5f5
color15 #000000
