# Generated by ./theme.sh
FZF_THEME_ARGS=(
	--color=fg:#e4e4ef\,bg:#181818
	--color=fg+:#e4e4ef\,bg+:#282828
	--color=hl:#94b0a6:reverse:bold\,hl+:#94b0a6:reverse:bold
	--color=info:#585858\,separator:#52494e\,scrollbar:#52494e\,border:#52494e
	--color=prompt:#73d936\,pointer:#565f73\,marker:#565f73\,spinner:#94b0a6\,header:#676666
)
