#!/usr/bin/env bash

THEME_HOME="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
THEME_THEMES_DIR="$THEME_HOME/themes"
THEME_FZF_FILE="$THEME_HOME/current_fzf"
THEME_NVIM_INIT_FILE="$HOME/.config/nvim/init.lua"
THEME_KITTY_CURRENT_FILE="$HOME/.config/kitty/current-theme.conf"
THEME_WINDOWS_TERMINAL_SETTINGS_PATH="${WINDOWS_TERMINAL_SETTINGS_PATH:-/mnt/c/Users/yiann/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json}"

required_theme_vars=(
	THEME_NAME
	THEME_NVIM_NAME
	THEME_VARIANT
	THEME_BACKGROUND
	THEME_BACKGROUND_ALT
	THEME_SURFACE
	THEME_SURFACE_ALT
	THEME_OVERLAY
	THEME_MUTED
	THEME_SUBTLE
	THEME_FOREGROUND
	THEME_RED
	THEME_YELLOW
	THEME_ORANGE
	THEME_BLUE
	THEME_CYAN
	THEME_LAVENDER
	THEME_MAGENTA
	THEME_GREEN
	THEME_HIGHLIGHT
	THEME_SELECTION
	THEME_BORDER
)

trim() {
	local value="$1"
	value="${value#"${value%%[![:space:]]*}"}"
	value="${value%"${value##*[![:space:]]}"}"
	printf '%s\n' "$value"
}

strip_quotes() {
	local value="$1"
	[[ "$value" == \"*\" && "$value" == *\" ]] && value="${value:1:${#value}-2}"
	printf '%s\n' "$value"
}

escape_sed_replacement() {
	local value="$1"
	value="${value//\\/\\\\}"
	value="${value//&/\\&}"
	printf '%s\n' "$value"
}

theme_names() {
	local path name
	shopt -s nullglob
	for path in "$THEME_THEMES_DIR"/*.ini; do
		name="${path##*/}"
		printf '%s\n' "${name%.ini}"
	done | sort
	shopt -u nullglob
}

theme_set_var() {
	local key="$1" value="$2" var_name
	var_name="THEME_${key^^}"
	printf -v "$var_name" '%s' "$value"
}

theme_load() {
	local name="$1" file section line key value var_name
	file="$THEME_THEMES_DIR/$name.ini"
	section=''
	unset THEME_KDE_NAME
	for var_name in "${required_theme_vars[@]}"; do
		unset "$var_name"
	done

	[[ -f "$file" ]] || {
		printf 'Theme file not found: %s\n' "$file" >&2
		return 1
	}

	while IFS= read -r line || [[ -n "$line" ]]; do
		line="$(trim "$line")"
		[[ -z "$line" || "$line" == '#'* || "$line" == ';'* ]] && continue

		if [[ "$line" =~ ^\[([a-z_]+)\]$ ]]; then
			section="${BASH_REMATCH[1]}"
			[[ "$section" == meta || "$section" == palette ]] || {
				printf 'Unsupported theme section [%s] in %s\n' "$section" "$file" >&2
				return 1
			}
			continue
		fi

		[[ "$section" =~ ^(meta|palette)$ && "$line" =~ ^([a-z_]+)[[:space:]]*=[[:space:]]*(.+)$ ]] || {
			printf 'Invalid theme line in %s: %s\n' "$file" "$line" >&2
			return 1
		}

		key="${BASH_REMATCH[1]}"
		value="$(strip_quotes "$(trim "${BASH_REMATCH[2]}")")"
		theme_set_var "$key" "$value"
	done <"$file"

	for var_name in "${required_theme_vars[@]}"; do
		[[ -n "${!var_name:-}" ]] || {
			printf 'Theme %s is missing %s\n' "$name" "$var_name" >&2
			return 1
		}
	done

	[[ "$THEME_VARIANT" == dark || "$THEME_VARIANT" == light ]] || {
		printf 'Theme variant must be dark or light: %s\n' "$THEME_VARIANT" >&2
		return 1
	}
}

theme_write_fzf() {
	{
		printf '%s\n' "--color=fg:${THEME_FOREGROUND},bg:${THEME_BACKGROUND}"
		printf '%s\n' "--color=fg+:${THEME_FOREGROUND},bg+:${THEME_SELECTION}"
		printf '%s\n' "--color=hl:${THEME_HIGHLIGHT}:reverse:bold,hl+:${THEME_HIGHLIGHT}:reverse:bold"
		printf '%s\n' "--color=info:${THEME_MUTED},separator:${THEME_OVERLAY},scrollbar:${THEME_OVERLAY},border:${THEME_OVERLAY}"
	} >"$THEME_FZF_FILE"
}

theme_apply_nvim() {
	local variant colorscheme server remote_cmd

	if [[ -f "$THEME_NVIM_INIT_FILE" ]]; then
		variant="$(escape_sed_replacement "$THEME_VARIANT")"
		colorscheme="$(escape_sed_replacement "$THEME_NVIM_NAME")"
		sed -i -E "s|^([[:space:]]*vim\.opt\.background[[:space:]]*=[[:space:]]*).*$|\\1\"${variant}\"|" "$THEME_NVIM_INIT_FILE"
		sed -i -E "s|^([[:space:]]*vim\.cmd\.colorscheme\()[^)]*(\).*)$|\\1\"${colorscheme}\"\\2|" "$THEME_NVIM_INIT_FILE"
	fi

	[[ -n "${XDG_RUNTIME_DIR:-}" ]] || return 0
	remote_cmd="<Esc>:set background=${THEME_VARIANT}<CR>:colorscheme ${THEME_NVIM_NAME}<CR>"
	shopt -s nullglob
	for server in "$XDG_RUNTIME_DIR"/nvim.*; do
		nvim --server "$server" --remote-send "$remote_cmd" >/dev/null 2>&1 || true
	done
	shopt -u nullglob
}

kitty_line() {
	printf '%-24s %s\n' "$1" "$2"
}

theme_apply_kitty() {
	{
		printf '# vim:ft=kitty\n\n'
		printf '## Generated by %s\n' "${BASH_SOURCE[0]}"
		printf '## name: %s\n' "$THEME_NAME"
		printf '## variant: %s\n\n' "$THEME_VARIANT"
		printf '# The basic colors\n'
		kitty_line foreground "$THEME_FOREGROUND"
		kitty_line background "$THEME_BACKGROUND"
		kitty_line selection_foreground "$THEME_FOREGROUND"
		kitty_line selection_background "$THEME_SELECTION"
		printf '\n# Cursor colors\n'
		kitty_line cursor "$THEME_FOREGROUND"
		kitty_line cursor_text_color "$THEME_BACKGROUND"
		printf '\n# kitty window border colors\n'
		kitty_line active_border_color "$THEME_BLUE"
		kitty_line inactive_border_color "$THEME_BORDER"
		printf '\n# Tab bar colors\n'
		kitty_line active_tab_foreground "$THEME_FOREGROUND"
		kitty_line active_tab_background "$THEME_SURFACE"
		kitty_line inactive_tab_foreground "$THEME_MUTED"
		kitty_line inactive_tab_background "$THEME_BACKGROUND_ALT"
		printf '\n# The basic 16 colors\n\n'
		printf '# black\n'
		kitty_line color0 "$THEME_BACKGROUND_ALT"
		kitty_line color8 "$THEME_MUTED"
		printf '\n# red\n'
		kitty_line color1 "$THEME_RED"
		kitty_line color9 "$THEME_RED"
		printf '\n# green\n'
		kitty_line color2 "$THEME_GREEN"
		kitty_line color10 "$THEME_GREEN"
		printf '\n# yellow\n'
		kitty_line color3 "$THEME_YELLOW"
		kitty_line color11 "$THEME_ORANGE"
		printf '\n# blue\n'
		kitty_line color4 "$THEME_BLUE"
		kitty_line color12 "$THEME_LAVENDER"
		printf '\n# magenta\n'
		kitty_line color5 "$THEME_MAGENTA"
		kitty_line color13 "$THEME_LAVENDER"
		printf '\n# cyan\n'
		kitty_line color6 "$THEME_CYAN"
		kitty_line color14 "$THEME_CYAN"
		printf '\n# white\n'
		kitty_line color7 "$THEME_SURFACE_ALT"
		kitty_line color15 "$THEME_FOREGROUND"
	} >"$THEME_KITTY_CURRENT_FILE"

	command -v kitty >/dev/null 2>&1 && kitty @ load-config >/dev/null 2>&1 || true
}

theme_apply_windows_terminal() {
	local scheme variant
	[[ -f "$THEME_WINDOWS_TERMINAL_SETTINGS_PATH" ]] || return 0

	scheme="$(escape_sed_replacement "$THEME_NAME")"
	variant="$(escape_sed_replacement "$THEME_VARIANT")"
	sed -i -E "s|^([[:space:]]*\"colorScheme\"[[:space:]]*:[[:space:]]*).*$|\\1\"${scheme}\",|" "$THEME_WINDOWS_TERMINAL_SETTINGS_PATH"
	sed -i -E "s|^([[:space:]]*\"theme\"[[:space:]]*:[[:space:]]*).*$|\\1\"${variant}\",|" "$THEME_WINDOWS_TERMINAL_SETTINGS_PATH"
}

theme_apply_kde() {
	[[ -n "${THEME_KDE_NAME:-}" ]] || return 0
	command -v plasma-apply-colorscheme >/dev/null 2>&1 && plasma-apply-colorscheme "$THEME_KDE_NAME" >/dev/null 2>&1 || true
	command -v qdbus6 >/dev/null 2>&1 || return 0

	qdbus6 org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
	for (const d of desktops()) {
		d.wallpaperPlugin = 'org.kde.color';
		d.currentConfigGroup = ['Wallpaper', 'org.kde.color', 'General'];
		d.writeConfig('Color', '${THEME_BACKGROUND}');
	}"
}

theme_apply() {
	theme_load "$1" || return 1
	theme_write_fzf
	theme_apply_nvim

	if [[ "$(uname -s)" == Linux && -d /mnt/c/Windows ]]; then
		theme_apply_windows_terminal
	elif [[ "$(uname -s)" == Linux ]]; then
		theme_apply_kitty
		theme_apply_kde
	fi
}

theme_pick() {
	local selected
	selected="$(theme_names | fzf --border=rounded)" || return 1
	[[ -n "$selected" ]] || return 1

	if [[ "${THEME_PICKER_BACKGROUND:-0}" == 1 && -n "${TMUX:-}" ]]; then
		case "$selected" in
		*[!A-Za-z0-9._-]*)
			printf 'Invalid theme name: %s\n' "$selected" >&2
			return 1
			;;
		esac

		tmux run-shell -b "~/.config/theme/theme.sh apply '$selected' >/dev/null 2>&1"
		return 0
	fi

	theme_apply "$selected"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	case "${1:-pick}" in
	pick)
		theme_pick
		;;
	apply)
		shift
		[[ -n "${1:-}" ]] || {
			printf 'Usage: %s apply <theme>\n' "$0" >&2
			exit 2
		}
		theme_apply "$1"
		;;
	*)
		printf 'Usage: %s [pick|apply <theme>]\n' "$0" >&2
		exit 2
		;;
	esac
fi
