-- vim.opt.tabstop = 4      -- a tab shows as 4 spaces
-- vim.opt.shiftwidth = 4  -- indent size
--
-- vim.opt.expandtab = true -- use spaces instead of tabs
-- vim.opt.softtabstop = 4 -- <Tab>/<BS> behave like 4 spaces
--
