preload = /home/karavellas/.config/hypr/BG-archlinux-logo-white-1200dpi.png

wallpaper {
    monitor = DP-1
    path = /home/karavellas/.config/hypr/BG-archlinux-logo-white-1200dpi.png
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/karavellas/.config/hypr/BG-archlinux-logo-white-1200dpi.png
}
