return {
    -- The rose-pine colorscheme plugin
    {
        "rose-pine/neovim",
        name = "rose-pine",
        config = function()
            require("rose-pine").setup({
                variant = "auto",
                dark_variant = "moon",
                dim_inactive_windows = true,
                disable_float_background = true,
                styles = {
                    transparency = false,
                },
                palette = {
                    moon = {
                        bg = "#000000",
                        _nc = "#000000",
                        base = "#16151a",
                        surface = "#1c1c24",
                        overlay = "#252530",
                        muted = "#56526e",
                        subtle = "#6e6a86",
                        text = "#e9e9e9",
                        love = "#de7e93",
                        gold = "#e8bb94",
                        rose = "#cd9696",
                        pine = "#7a9dc8",
                        foam = "#9f9fcf",
                        iris = "#b993bc",
                        leaf = "#a7c1bd",
                        highlight_low = "#1a1826",
                        highlight_med = "#2a283e",
                        highlight_high = "#44415a",
                        none = "NONE",
                    },
                },
                highlight_groups = {
                    Normal = { fg = "text", bg = "bg" },
                    IncSearch = { fg = "base", bg = "rose" },
                    -- Set floating windows to use terminal background
                    NormalFloat = { fg = "text", bg = "bg" },
                    FloatBorder = { fg = "muted", bg = "bg" },
                    YankHighlight = { fg = "base", bg = "subtle" },
                    -- Snacks picker specific
                    SnacksPicker = { fg = "text", bg = "bg" },
                    SnacksPickerBorder = { fg = "muted", bg = "bg" },
                    SnacksPickerList = { fg = "text", bg = "bg" },
                    SnacksPickerPreview = { fg = "text", bg = "bg" },
                    SnacksPickerInput = { fg = "text", bg = "bg" },
                    BlinkCmpMenu = { fg = "text", bg = "bg" },
                    BlinkCmpMenuBorder = { fg = "muted", bg = "bg" },
                    BlinkCmpMenuSelection = { fg = "text", bg = "highlight_low" },
                    BlinkCmpScrollBarThumb = { bg = "muted" },
                    BlinkCmpScrollBarGutter = { bg = "bg" },
                    BlinkCmpLabel = { fg = "text", bg = "bg" },
                    BlinkCmpLabelDeprecated = { fg = "muted", bg = "bg" },
                    BlinkCmpLabelMatch = { fg = "rose", bg = "bg" },
                    BlinkCmpLabelDetail = { fg = "subtle", bg = "bg" },
                    BlinkCmpLabelDescription = { fg = "subtle", bg = "bg" },
                    BlinkCmpKind = { fg = "iris", bg = "bg" },
                    BlinkCmpSource = { fg = "muted", bg = "bg" },
                    BlinkCmpGhostText = { fg = "muted", bg = "none" },
                    BlinkCmpDoc = { fg = "text", bg = "bg" },
                    BlinkCmpDocBorder = { fg = "muted", bg = "bg" },
                    BlinkCmpDocSeparator = { fg = "muted", bg = "bg" },
                    BlinkCmpDocCursorLine = { bg = "highlight_low" },
                    BlinkCmpSignatureHelp = { fg = "text", bg = "bg" },
                    BlinkCmpSignatureHelpBorder = { fg = "muted", bg = "bg" },
                    BlinkCmpSignatureHelpActiveParameter = { fg = "rose", bg = "bg" },
                    -- Active line highlighting
                    CursorLine = { bg = "highlight_low" },
                    -- Visual selection highlighting
                    Visual = { bg = "#6f6fca" },
                    FloatTitle = { fg = "text", bg = "bg" },
                },
            })
        end,
    },
}
