return {
    "vague2k/vague.nvim",
    "pompos02/modus-themes.nvim",
    "folke/tokyonight.nvim",
    -- "pompos02/yara.nvim",
    { dir = "/Users/yianniscaravellas/projects/opensource/yara.nvim" },
    { dir = "/Users/yianniscaravellas/projects/opensource/dolores.nvim" },
    { dir = "/Users/yianniscaravellas/projects/opensource/misirloun" },
    { dir = "/Users/yianniscaravellas/projects/opensource/ysolarized.nvim" },
    "neanias/everforest-nvim",
    "sainnhe/sonokai",
    "navarasu/onedark.nvim",
    "rose-pine/neovim",
    "kepano/flexoki-neovim",
    "f4z3r/gruvbox-material.nvim",
    "whizikxd/naysayer-colors.nvim",
    "mountain-theme/vim",
    "oskarnurm/koda.nvim",
    "catppuccin/nvim",
    "rebelot/kanagawa.nvim",
    "scottmckendry/cyberdream.nvim",
    "metalelf0/jellybeans-nvim",
    "bluz71/vim-moonfly-colors",
    "slugbyte/lackluster.nvim",
    "ThunderBoltCODMYT/gruber-darker.vim",
    "morhetz/gruvbox",
    "EdenEast/nightfox.nvim",
    "RostislavArts/naysayer.nvim",
}
