return {
    "vague2k/vague.nvim",
    "pompos02/misirlou.nvim",
    "pompos02/modus-themes.nvim",
    "folke/tokyonight.nvim",
    "craftzdog/solarized-osaka.nvim",
    -- "pompos02/yara.nvim",
    { dir = "/home/karavellas/projects/opensource/yara.nvim" },
    { "zenbones-theme/zenbones.nvim", dependencies = "rktjmp/lush.nvim", lazy = false, priority = 1000, },
    "navarasu/onedark.nvim",
    "rose-pine/neovim",
    "mountain-theme/vim",
    "oskarnurm/koda.nvim",
    "rebelot/kanagawa.nvim",
    "scottmckendry/cyberdream.nvim",
    "bluz71/vim-moonfly-colors",
    "slugbyte/lackluster.nvim",
    "blazkowolf/gruber-darker.nvim",
}
