[general]
live_config_reload = true
import = ["~/.config/alacritty/theme.toml"]

# [font.normal]
# family = "TX-02"
# style = "Medium"
#
# [font.bold]
# family = "TX-02"
# style = "ExtraBold"
#
# [font.italic]
# family = "TX-02"
# style = "Oblique"
#
# [font.bold_italic]
# family = "TX-02"
# style = "ExtraBold Oblique"

[font.normal]    
family = "TX-02M"
# style = "Medium" 

[font]
size = 15.0

[bell]
duration = 0

[window]
startup_mode = "Maximized"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]

[mouse]
hide_when_typing=true

[colors]
draw_bold_text_with_bright_colors = true
